### ISSUE TITLE
Transfer to cider org

### ISSUE THREAD

**Issue by cemerick** [clojure-emacs/piggieback#81]
So @bhauman suggested that piggieback might find a new home under the cider org. What say you, @bbatsov?

**Comment by bbatsov** [comment]
👍 Sounds like a good plan to me. nREPL and piggieback are very important to CIDER and being able to improve them when needed would be quite useful. I'll invite both of you to `clojure-emacs`, so you can initiative the transfer.

**Comment by cemerick** [comment]
Done.
