### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/piggieback#85]
@bhauman I guess we should cut a new release, but I can't do this myself.

I also wonder why are deploying this to central instead of to clojars.

**Comment by bhauman** [comment]
Yeah I would prefer clojars as well.  

Am I wrong to think that we should just publish under clojure-emacs?

**Comment by bbatsov** [comment]
I publish the `clojure-emacs` packages under `cider`, as I don't like the idea of having an editor in a package's name. If you're fine with this - let's make it happen. :-)

**Comment by bhauman** [comment]
Yeah that's what I was intending, sounds good to me.

**Comment by bbatsov** [comment]
OK, I've cut a new release with the updated coordinates. Down the road we should also change the ns I guess, but I'm not sure what's the best way to do this.

**Comment by bbatsov** [comment]
OK, 0.2.3 is out!

I'll grant you access to clojars, so you can cut releases as well.

**Comment by bhauman** [comment]
Fantastic!
